CREATE DATABASE IF NOT EXISTS sucai_meta
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE sucai_meta;

CREATE TABLE IF NOT EXISTS meta_source (
  id BIGINT NOT NULL AUTO_INCREMENT,
  source_id VARCHAR(64) NOT NULL,
  source_name VARCHAR(128) NOT NULL,
  endpoint VARCHAR(512) NOT NULL,
  minio_version VARCHAR(128) NOT NULL,
  service_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  config_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_source_source_id (source_id),
  KEY idx_meta_source_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_target (
  id BIGINT NOT NULL AUTO_INCREMENT,
  target_id VARCHAR(64) NOT NULL,
  target_name VARCHAR(128) NOT NULL,
  endpoint VARCHAR(512) NOT NULL,
  minio_version VARCHAR(128) NOT NULL,
  cold_bucket VARCHAR(255) NOT NULL,
  cold_prefix VARCHAR(1024) NOT NULL,
  tier_name VARCHAR(128) NOT NULL,
  usable_free_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  config_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_target_target_id (target_id),
  UNIQUE KEY uk_meta_target_tier (target_id, cold_bucket, tier_name),
  KEY idx_meta_target_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_migration_batch (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id VARCHAR(128) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  source_bucket VARCHAR(255) NOT NULL,
  cold_bucket VARCHAR(255) NOT NULL,
  cold_prefix VARCHAR(1024) NOT NULL,
  tier_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  max_migratable_bytes BIGINT UNSIGNED NULL,
  planned_object_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  transitioned_object_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  planned_object_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  transitioned_object_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  manifest_uri VARCHAR(1024) NULL,
  started_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_migration_batch_batch_id (batch_id),
  KEY idx_meta_migration_batch_source_status (source_id, status),
  KEY idx_meta_migration_batch_target_status (target_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_video (
  id BIGINT NOT NULL AUTO_INCREMENT,
  source_id VARCHAR(64) NOT NULL,
  company_id BIGINT NOT NULL,
  station_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  user_id BIGINT NULL,
  account_id BIGINT NULL,
  video_status VARCHAR(64) NULL,
  business_create_time DATETIME NULL,
  business_update_time DATETIME NULL,
  migration_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  required_object_count INT UNSIGNED NOT NULL DEFAULT 0,
  verified_object_count INT UNSIGNED NOT NULL DEFAULT 0,
  transitioned_object_count INT UNSIGNED NOT NULL DEFAULT 0,
  mapped_object_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_video_identity (source_id, company_id, station_id, video_id),
  KEY idx_meta_video_company_station_status (company_id, station_id, migration_status),
  KEY idx_meta_video_video_id (video_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_batch_video (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id VARCHAR(128) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  company_id BIGINT NOT NULL,
  station_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  meta_video_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_batch_video_identity (batch_id, source_id, company_id, station_id, video_id),
  KEY idx_meta_batch_video_video (source_id, company_id, station_id, video_id),
  KEY idx_meta_batch_video_status (batch_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_object (
  id BIGINT NOT NULL AUTO_INCREMENT,
  source_id VARCHAR(64) NOT NULL,
  company_id BIGINT NOT NULL,
  station_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  file_role VARCHAR(64) NOT NULL,
  required_role TINYINT(1) NOT NULL DEFAULT 1,
  source_bucket VARCHAR(255) NOT NULL,
  source_key TEXT NOT NULL,
  source_key_sha256 CHAR(64) NOT NULL,
  source_version_id VARCHAR(255) NOT NULL DEFAULT '',
  source_etag VARCHAR(255) NULL,
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sha256 CHAR(64) NULL,
  content_type VARCHAR(512) NULL,
  user_metadata_json JSON NULL,
  last_modified DATETIME NULL,
  object_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  storage_class VARCHAR(128) NULL,
  transition_batch_id VARCHAR(128) NULL,
  transition_time DATETIME NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_object_source_key (source_id, source_bucket, source_key_sha256, source_version_id),
  UNIQUE KEY uk_meta_object_business_role (source_id, company_id, station_id, video_id, file_role, source_bucket, source_key_sha256, source_version_id),
  KEY idx_meta_object_business_video (source_id, company_id, station_id, video_id),
  KEY idx_meta_object_batch_status (transition_batch_id, object_status),
  KEY idx_meta_object_status (object_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_object_mapping (
  id BIGINT NOT NULL AUTO_INCREMENT,
  meta_object_id BIGINT NULL,
  source_id VARCHAR(64) NOT NULL,
  company_id BIGINT NOT NULL,
  station_id BIGINT NOT NULL,
  video_id BIGINT NOT NULL,
  file_role VARCHAR(64) NOT NULL,
  source_bucket VARCHAR(255) NOT NULL,
  source_key TEXT NOT NULL,
  source_key_sha256 CHAR(64) NOT NULL,
  source_version_id VARCHAR(255) NOT NULL DEFAULT '',
  source_size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_sha256 CHAR(64) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  cold_bucket VARCHAR(255) NOT NULL,
  cold_prefix VARCHAR(1024) NOT NULL,
  cold_object_key TEXT NOT NULL,
  cold_object_key_sha256 CHAR(64) NOT NULL,
  cold_size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cold_sha256 CHAR(64) NOT NULL,
  tier_name VARCHAR(128) NOT NULL,
  transition_batch_id VARCHAR(128) NOT NULL,
  match_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  verify_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  restore_status VARCHAR(32) NOT NULL DEFAULT 'NOT_RESTORED',
  delete_status VARCHAR(32) NOT NULL DEFAULT 'NOT_DELETED',
  ambiguity_group_id VARCHAR(128) NULL,
  transition_time DATETIME NULL,
  mapped_at DATETIME(6) NULL,
  verified_at DATETIME(6) NULL,
  restored_at DATETIME(6) NULL,
  deleted_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_mapping_source_object (source_id, source_bucket, source_key_sha256, source_version_id),
  UNIQUE KEY uk_meta_mapping_business_role (source_id, company_id, station_id, video_id, file_role, source_bucket, source_key_sha256, source_version_id),
  KEY idx_meta_mapping_business_video (source_id, company_id, station_id, video_id),
  KEY idx_meta_mapping_cold_object (target_id, cold_bucket, cold_object_key_sha256),
  KEY idx_meta_mapping_batch_status (transition_batch_id, verify_status, restore_status),
  KEY idx_meta_mapping_delete_status (delete_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_event_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id VARCHAR(128) NULL,
  source_id VARCHAR(64) NULL,
  company_id BIGINT NULL,
  station_id BIGINT NULL,
  video_id BIGINT NULL,
  object_id BIGINT NULL,
  event_type VARCHAR(64) NOT NULL,
  event_level VARCHAR(16) NOT NULL DEFAULT 'INFO',
  message TEXT NOT NULL,
  detail_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_meta_event_batch_time (batch_id, created_at),
  KEY idx_meta_event_business_video (source_id, company_id, station_id, video_id),
  KEY idx_meta_event_type_time (event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meta_sync_receipt (
  id BIGINT NOT NULL AUTO_INCREMENT,
  client_request_id VARCHAR(128) NOT NULL,
  batch_id VARCHAR(128) NULL,
  source_id VARCHAR(64) NULL,
  operation VARCHAR(64) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  response_status VARCHAR(32) NOT NULL,
  response_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_meta_sync_receipt_request (client_request_id),
  KEY idx_meta_sync_receipt_batch (batch_id, operation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
